### PR TITLE
feature: types

### PR DESCRIPTION
**Pull request by elgorditosalsero**
Added types to enable support for TypeScript.

### CODE REVIEW

**Comment by astagi** [comment]
Thanks @elgorditosalsero !  looks great! I added `Validator.validate` in the meantime, is it possible to add?
```js
 const validationResult = await Validator.validate(myDCC);
```
that returns an object like this

```js
{
  person: 'Erika Mustermann',
  date_of_birth: '1964-08-12',
  code: 'NOT_VALID',
  result: false,
  message: 'Test Result is expired at : 2021-05-22T12:34:56.000Z'
}
```

**Comment by elgorditosalsero** [comment]
> Thanks @elgorditosalsero !  looks great! I added `Validator.validate` in the meantime, is it possible to add?
> 
> ```js
> 
>  const validationResult = await Validator.validate(myDCC);
> 
> ```
> 
> that returns an object like this
> 
> 
> 
> ```js
> 
> {
> 
>   person: 'Erika Mustermann',
> 
>   date_of_birth: '1964-08-12',
> 
>   code: 'NOT_VALID',
> 
>   result: false,
> 
>   message: 'Test Result is expired at : 2021-05-22T12:34:56.000Z'
> 
> }
> 
> ```

Hi @astagi,

Yeah, for sure, will do as soon as possible ☺️

**Comment by elgorditosalsero** [comment]
@astagi Added the `validate` method types and improved some others 👍🏽

**Review by astagi — APPROVED** [review]

**Comment by astagi** [comment]
Thank you @elgorditosalsero 🙌

**Pull request merged**
